// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"coding-games/config"
	"coding-games/infrastructure/server"
	"coding-games/internal/handler/gamehdl"
	"coding-games/internal/handler/leaderboardhdl"
	"coding-games/internal/handler/playerhdl"
	"coding-games/internal/storage"
	"github.com/gofiber/fiber/v3"
	"log"
)

// Injectors from main.go:

func initialize() *dependencies {
	storageStorage := storage.NewInMemoryStorage()
	handler := gamehdl.New(storageStorage)
	playerhdlHandler := playerhdl.New(storageStorage)
	leaderboardhdlHandler := leaderboardhdl.New(storageStorage)
	app := server.New(handler, playerhdlHandler, leaderboardhdlHandler)
	mainDependencies := &dependencies{
		server: app,
	}
	return mainDependencies
}

// main.go:

type dependencies struct {
	server *fiber.App
}

func main() {
	d := initialize()
	log.Printf("Server is running on port %s", config.Get().Server.Port)

	defer func() {
		if err := d.server.Shutdown(); err != nil {
			log.Printf("Error during shutdown: %s", err.Error())
		}
		log.Println("Server gracefully stopped")
	}()

	if err := d.server.Listen(":" + config.Get().Server.Port); err != nil {
		log.Fatalf("Failed to start server: %s", err.Error())
	}
}
